In [ ]:
import pandas as pd

df = pd.read_csv('test.csv')

In [ ]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [ ]:
df.tail()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
df.count()

Year                           55620
Industry_aggregation_NZSIOC    55620
Industry_code_NZSIOC           55620
Industry_name_NZSIOC           55620
Units                          55620
Variable_code                  55620
Variable_name                  55620
Variable_category              55620
Value                          55620
Industry_code_ANZSIC06         55620
dtype: int64

In [ ]:
df.isnull()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
55615,False,False,False,False,False,False,False,False,False,False
55616,False,False,False,False,False,False,False,False,False,False
55617,False,False,False,False,False,False,False,False,False,False
55618,False,False,False,False,False,False,False,False,False,False
55619,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.loc[1,'Variable_code']

'H04'

In [ ]:
df.iloc[1,5]

'H04'

In [ ]:
df.describe(include='all')

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
count,55620.000000,55620,55620,55620,55620,55620,55620,55620,55620,55620
unique,NaN,3,139,119,3,39,41,3,14801,119
top,NaN,Level 4,CC41,"Public Order, Safety and Regulatory Services",Dollars (millions),H01,Total income,Financial performance,C,ANZSIC06 groups C151 and C152
freq,NaN,30444,432,1054,43728,1668,1668,27804,2388,864
mean,2018.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.452084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2015.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2018.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2021.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = pd.read_csv('test.csv')
df[df['Year'] > 2014]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
46345,2015,Level 3,ZZ11,Food Product Manufacturing,Percentage,H37,Quick ratio,Financial ratios,74,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
46346,2015,Level 3,ZZ11,Food Product Manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,28,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
46347,2015,Level 3,ZZ11,Food Product Manufacturing,Percentage,H39,Return on equity,Financial ratios,17,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
46348,2015,Level 3,ZZ11,Food Product Manufacturing,Percentage,H40,Return on total assets,Financial ratios,8,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
46349,2015,Level 3,ZZ11,Food Product Manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
df.rename(columns={'Units':'UNIT'})

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,UNIT,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
df.set_index('Value', inplace=True)

In [ ]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Industry_code_ANZSIC06
Value,,,,,,,,,
979594,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,ANZSIC06 divisions A-S (excluding classes K633...
838626,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,ANZSIC06 divisions A-S (excluding classes K633...
112188,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,ANZSIC06 divisions A-S (excluding classes K633...
28781,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,ANZSIC06 divisions A-S (excluding classes K633...
856960,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,ANZSIC06 divisions A-S (excluding classes K633...

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df.isnull()

,Value,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Industry_code_ANZSIC06
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
55615,False,False,False,False,False,False,False,False,False,False
55616,False,False,False,False,False,False,False,False,False,False
55617,False,False,False,False,False,False,False,False,False,False
55618,False,False,False,False,False,False,False,False,False,False
55619,False,False,False,False,False,False,False,False,False,False

In [ ]:
pd.crosstab(df['Year'], df['Units'])

Units  Dollars  Dollars (millions)  Percentage
Year
2013       254                3644         737
2014       254                3644         737
2015       254                3644         737
2016       254                3644         737
2017       254                3644         737
2018       254                3644         737
2019       254                3644         737
2020       254                3644         737
2021       254                3644         737
2022       254                3644         737
2023       254                3644         737
2024       254                3644         737

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2, 3]}, index=['a', 'b', 'c'])
df2 = pd.DataFrame({'B': [4, 5, 6]}, index=['a', 'b', 'd'])

print(df1, "\n")
print(df2, "\n")

# joins on index
res = df1.join(df2, how='inner')
print(res)

   A
a  1
b  2
c  3

   B
a  4
b  5
d  6

   A  B
a  1  4
b  2  5

In [ ]:
df_cleaned = df.drop_duplicates()

In [ ]:
print(df_cleaned)

        Value  Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      979594  2024                     Level 1                99999
1      838626  2024                     Level 1                99999
2      112188  2024                     Level 1                99999
3       28781  2024                     Level 1                99999
4      856960  2024                     Level 1                99999
...       ...   ...                         ...                  ...
55615      52  2013                     Level 3                 ZZ11
55616      40  2013                     Level 3                 ZZ11
55617      12  2013                     Level 3                 ZZ11
55618       5  2013                     Level 3                 ZZ11
55619      46  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

                                  Industry_code_ANZSIC06
0      ANZSIC06 divisions A-S (excluding classes K633...
1      ANZSIC06 divisions A-S (excluding classes K633...
2      ANZSIC06 divisions A-S (excluding classes K633...
3      ANZSIC06 divisions A-S (excluding classes K633...
4      ANZSIC06 divisions A-S (excluding classes K633...
...                                                  ...
55615  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]

Practices

In [ ]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd

data = {
    'Name': ['John', 'Anna', 'Mike'],
    'Age': [25, 30, 35]
}

df = pd.DataFrame(data)

print(df)

   Name  Age
0  John   25
1  Anna   30
2  Mike   35

In [ ]:
import pandas as pd

df = pd.read_csv("test.csv")

print(df.head())

   Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2024                     Level 1                99999       All industries
1  2024                     Level 1                99999       All industries
2  2024                     Level 1                99999       All industries
3  2024                     Level 1                99999       All industries
4  2024                     Level 1                99999       All industries

                Units Variable_code  \
0  Dollars (millions)           H01
1  Dollars (millions)           H04
2  Dollars (millions)           H05
3  Dollars (millions)           H07
4  Dollars (millions)           H08

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance
1  Sales, government funding, grants and subsidies  Financial performance
2                Interest, dividends and donations  Financial performance
3                             Non-operating income  Financial performance
4                                Total expenditure  Financial performance

    Value                             Industry_code_ANZSIC06
0  979594  ANZSIC06 divisions A-S (excluding classes K633...
1  838626  ANZSIC06 divisions A-S (excluding classes K633...
2  112188  ANZSIC06 divisions A-S (excluding classes K633...
3   28781  ANZSIC06 divisions A-S (excluding classes K633...
4  856960  ANZSIC06 divisions A-S (excluding classes K633...

In [ ]:
import pandas as pd

df = pd.read_csv("test.csv")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55620 entries, 0 to 55619
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         55620 non-null  int64
 1   Industry_aggregation_NZSIOC  55620 non-null  object
 2   Industry_code_NZSIOC         55620 non-null  object
 3   Industry_name_NZSIOC         55620 non-null  object
 4   Units                        55620 non-null  object
 5   Variable_code                55620 non-null  object
 6   Variable_name                55620 non-null  object
 7   Variable_category            55620 non-null  object
 8   Value                        55620 non-null  object
 9   Industry_code_ANZSIC06       55620 non-null  object
dtypes: int64(1), object(9)
memory usage: 4.2+ MB
None

In [ ]:
import pandas as pd

data = {
    'Name': ['John', 'Anna'],
    'Age': [25, 30]
}

df = pd.DataFrame(data)

print(df['Name'])

In [ ]:
import pandas as pd

data = {
    'Name': ['John', 'Anna', 'Mike'],
    'Age': [25, 30, 35]
}

df = pd.DataFrame(data)

filtered = df[df['Age'] > 25]

print(filtered)

   Name  Age
1  Anna   30
2  Mike   35

In [ ]:
import pandas as pd

data = {
    'A': [1, 2, 3]
}

df = pd.DataFrame(data)

df['B'] = [4, 5, 6]

print(df)

   A  B
0  1  4
1  2  5
2  3  6

In [ ]:
import pandas as pd
import numpy as np

data = {
    'A': [1, np.nan, 3]
}

df = pd.DataFrame(data)

df_filled = df.fillna(0)

print(df_filled)

In [ ]:
import pandas as pd

data = {
    'Department': ['HR', 'IT', 'HR', 'IT'],
    'Salary': [3000, 4000, 3500, 4500]
}

df = pd.DataFrame(data)

grouped = df.groupby('Department')['Salary'].mean()

print(grouped)

In [ ]:
import pandas as pd

df = pd.read_csv("input.csv")

df.to_csv("output.csv", index=False)

print("CSV file written successfully")

In [ ]:
import pandas as pd

data = {
    'Name': ['John', 'Anna', 'John', 'Mike'],
    'Age': [25, 30, 25, 35]
}

df = pd.DataFrame(data)

duplicates = df[df.duplicated()]

print(duplicates)

   Name  Age
2  John   25

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['John', 'Anna', 'Mike']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Salary': [5000, 6000, 7000]
})

merged = pd.merge(df1, df2, on='ID')

print(merged)

   ID  Name  Salary
0   1  John    5000
1   2  Anna    6000
2   3  Mike    7000

In [ ]:
import pandas as pd

data = {
    'Name': ['John', 'Anna', 'Mike'],
    'Age': [25, 30, 22]
}

df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age')

print(sorted_df)

   Name  Age
2  Mike   22
0  John   25
1  Anna   30

In [ ]:
import pandas as pd
import numpy as np

data = {
    'A': [1, np.nan, 3],
    'B': [4, 5, np.nan]
}

df = pd.DataFrame(data)

cleaned_df = df.fillna(df.mean())

print(cleaned_df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  4.5

In [ ]:
import pandas as pd

data = {
    'Department': ['HR', 'IT', 'HR', 'IT'],
    'Employee': ['A', 'B', 'C', 'D'],
    'Salary': [3000, 4000, 3500, 4500]
}

df = pd.DataFrame(data)

pivot = df.pivot_table(
    values='Salary',
    index='Department',
    aggfunc='mean'
)

print(pivot)

            Salary
Department
HR          3250.0
IT          4250.0

In [ ]:
import pandas as pd

data = {
    'Marks': [40, 50, 60]
}

df = pd.DataFrame(data)

df['Bonus'] = df['Marks'].apply(lambda x: x + 5)

print(df)

   Marks  Bonus
0     40     45
1     50     55
2     60     65

In [ ]:
import pandas as pd

data = {
    'A': [1, 2],
    'B': [3, 4]
}

df = pd.DataFrame(data)

df.columns = ['Number1', 'Number2']

print(df)

   Number1  Number2
0        1        3
1        2        4

In [ ]:
import pandas as pd

data = {
    'Name': ['John', 'Anna'],
    'Age': [25, 30]
}

df = pd.DataFrame(data)

df.to_excel('output.xlsx', index=False)

print("Excel file exported successfully")

Excel file exported successfully

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'old_name': [1, 2, 3]
})

df.rename(columns={'old_name': 'new_name'}, inplace=True)

print(df)

   new_name
0         1
1         2
2         3

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune']
})

print(df['City'].nunique())

3

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, np.nan, 3],
    'B': [4, 5, np.nan]
})

null_rows = df[df.isnull().any(axis=1)]

print(null_rows)

     A    B
1  NaN  5.0
2  3.0  NaN